<?php
namespace aura\signal;

/**
 * Test class for Manager.
 * Generated by PHPUnit on 2011-02-23 at 20:22:54.
 */
class ManagerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
    }

    public function newManager($handlers = null)
    {
        return new Manager(
            new HandlerFactory,
            new ResultFactory,
            new ResultCollection,
            $handlers
        );
    }
    
    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        parent::tearDown();
    }

    /**
     * @todo Implement testHandler().
     */
    public function testHandlerAndGetHandlers()
    {
        $signal = $this->newManager(array(
            // no position
            array(
                '\UnexpectedValueException',
                'mock_signal',
                array('MockAlpha', 'method')
            ),
            // early position
            array(
                '\StdClass',
                'mock_signal',
                array('MockBeta', 'method'),
                -5
            ),
            // late position
            array(
                '\Exception',
                'mock_signal',
                array('MockGamma', 'method'),
                +5
            ),
        ));
        
        // make sure they get sorted, which only happens on a signal send
        $signal->send(null, null);
        
        // now get them
        $handlers = $signal->getHandlers();
        
        // should be three position groups, in this order
        $expect = array(-5, 0, 5);
        $actual = array_keys($handlers);
        $this->assertSame($expect, $actual);
        
        // make sure the handlers are in the right groups
        $this->assertSame('\StdClass', $handlers[-5][0]->sender);
        $this->assertSame('\UnexpectedValueException', $handlers[0][0]->sender);
        $this->assertSame('\Exception', $handlers[+5][0]->sender);
    }
    
    /**
     * @todo Implement testSend().
     */
    public function testSend()
    {
        $signal = $this->newManager(array(
            // late position
            array(
                '\Unexpected',
                'mock_signal',
                function ($foo) { return "$foo-unexpected"; },
                +5
            ),
            // no position
            array(
                '\StdClass',
                'mock_signal',
                function ($foo) { return "$foo-stdclass-mid"; },
                0
            ),
            // early position
            array(
                '\StdClass',
                'mock_signal',
                function ($foo) { return "$foo-stdclass-early"; },
                -5
            ),
        ));
        
        // send a signal that should match two handlers
        $origin = new \StdClass;
        $collection = $signal->send($origin, 'mock_signal', 'hello');
        $this->assertTrue(count($collection) == 2);
        $this->assertSame('hello-stdclass-early', $collection[0]->value);
        $this->assertSame('hello-stdclass-mid', $collection[1]->value);
        
        // add a handler that stops processing
        $signal->handler(
            '\StdClass',
            'mock_signal',
            function ($foo) { return Manager::STOP; },
            -1 // just before the mid group
        );
        
        $collection = $signal->send($origin, 'mock_signal', 'hello');
        $this->assertTrue(count($collection) == 2);
        $this->assertSame('hello-stdclass-early', $collection[0]->value);
        $this->assertSame(Manager::STOP, $collection[1]->value);
    }
}
